export const game = [{
  property: 'app_name',
  label: '软件名称'
}, {
  property: 'version',
  label: '版本号'
}, {
  property: 'tele_num',
  label: '手机号'
}, {
  property: 'unique_id',
  label: '设备ID'
}, {
  property: 'task_id',
  label: '业务ID'
}, {
  property: 'task_name',
  label: '业务名称'
}, {
  property: 'task',
  label: '业务类型'
}, {
  property: 'start_time',
  label: '开始时间'
}, {
  property: 'event_time',
  label: '测试时间'
}, {
  property: 'app_version',
  label: '第三方app版本号'
}, {
  property: 'start_app_delay',
  label: '启动app时延ms'
}, {
  property: 'first_page_all_delay',
  label: '首页打开时延ms'
}, {
  property: 'first_page_jitter_upload',
  label: '首页打开上行抖动值ms'
}, {
  property: 'first_page_jitter_download',
  label: '首页打开下行抖动值ms'
}, {
  property: 'first_page_pkg_count_upload',
  label: '首页打开上行包个数'
}, {
  property: 'first_page_pkg_count_download',
  label: '首页打开下行包个数'
}, {
  property: 'first_page_pkg_interval_upload',
  label: '首页打开上行包间隔ms'
}, {
  property: 'first_page_pkg_interval_download',
  label: '首页打开下行包间隔ms'
}, {
  property: 'first_page_upload_byte',
  label: '首页打开上行字节数byte'
}, {
  property: 'first_page_download_byte',
  label: '首页打开下行字节数byte'
}, {
  property: 'game_play_all_duration',
  label: '游戏总时长ms'
}, {
  property: 'game_play_upload_min_rate',
  label: '游戏上行最小速率bps'
}, {
  property: 'game_play_upload_max_rate',
  label: '游戏上行最大速率bps'
}, {
  property: 'game_play_upload_avg_rate',
  label: '游戏上行平均速率bps'
}, {
  property: 'game_play_download_min_rate',
  label: '游戏下行最小速率bps'
}, {
  property: 'game_play_download_max_rate',
  label: '游戏下行最大速率bps'
}, {
  property: 'game_play_download_avg_rate',
  label: '游戏下行平均速率bps'
}, {
  property: 'game_play_jitter_upload',
  label: '游戏上行抖动值ms'
}, {
  property: 'game_play_jitter_download',
  label: '游戏下行抖动值ms'
}, {
  property: 'upload_all_byte',
  label: '游戏上行字节数byte'
}, {
  property: 'download_all_byte',
  label: '游戏下行字节数byte'
}, {
  property: 'upload_all_pkgs',
  label: '游戏上行总包数'
}, {
  property: 'download_all_pkgs',
  label: '游戏下行总包数'
}, {
  property: 'ip_max_vitality_count',
  label: 'ip最大活跃个数'
}, {
  property: 'max_vitality_ip',
  label: '最大活跃ip'
}, {
  property: 'ip_min_vitality_count',
  label: 'ip最小活跃个数'
}, {
  property: 'min_vitality_ip',
  label: '最小活跃ip'
}, {
  property: 'failed_reason_code',
  label: '失败原因码'
}, {
  property: 'failed_reason',
  label: '失败原因'
}, {
  property: 'province',
  label: '省份'
}, {
  property: 'city',
  label: '城市'
}, {
  property: 'address',
  label: '详细地址'
}, {
  property: 'latitude',
  label: '纬度'
}, {
  property: 'longitude',
  label: '经度'
}, {
  property: 'source',
  label: '定位来源'
}, {
  property: 'network_type_id',
  label: '网络类型id'
}, {
  property: 'network_name',
  label: '网络类型名'
}, {
  property: 'network_info_id',
  label: '网络信息类型ID'
}, {
  property: 'operator_id',
  label: '运营商id'
}, {
  property: 'operator',
  label: '运营商标识'
}, {
  property: 'internal_ip',
  label: '内网ip'
}, {
  property: 'external_ip',
  label: '外网ip'
}, {
  property: 'wlan_ssid',
  label: 'WLAN_SSID'
}, {
  property: 'wlan_rssi',
  label: 'WLAN_RSSI'
}, {
  property: 'gsm_lac',
  label: 'GSM_LAC'
}, {
  property: 'gsm_cid',
  label: 'GSM_CID'
}, {
  property: 'gsm_rxqual',
  label: 'GSM_RXQUAL'
}, {
  property: 'cdma_strength',
  label: 'CDMA场强'
}, {
  property: 'cdma_ecio',
  label: 'CDMA_Ec/Io'
}, {
  property: 'cdma_rssi',
  label: 'CDMA_RSSI'
}, {
  property: 'cdma_nid',
  label: 'CDMA_NID'
}, {
  property: 'cdma_bsid',
  label: 'CDMA_BSID'
}, {
  property: 'cdma_sid',
  label: 'CDMA_SID'
}, {
  property: 'evdo_snr',
  label: 'EVDO_SNR'
}, {
  property: 'evdo_ecio',
  label: 'EVDO_ECIO'
}, {
  property: 'evdo_rssi',
  label: 'EVDO_RSSI'
}, {
  property: 'wcdma_strength',
  label: 'WCDMA信号强度'
}, {
  property: 'wcdma_rscp',
  label: 'WCDMA_RSCP'
}, {
  property: 'wcdma_rssi',
  label: 'WCDMA_RSSI'
}, {
  property: 'wcdma_ecno',
  label: 'WCDMA_Ec/No'
}, {
  property: 'wcdma_cid',
  label: 'WCDMA_CID'
}, {
  property: 'wcdma_lac',
  label: 'WCDMA_LAC'
}, {
  property: 'wcdma_psc',
  label: 'WCDMA_PSC'
}, {
  property: 'tdscdma_dbm',
  label: 'TDSCDMA_DBM'
}, {
  property: 'tdscdma_rssi',
  label: 'TDSCDMA_RSSI'
}, {
  property: 'tdscdma_cid',
  label: 'TDSCDMA_CID'
}, {
  property: 'tdscdma_cpid',
  label: 'TDSCDMA_CPID'
}, {
  property: 'tdscdma_lac',
  label: 'TDSCDMA_LAC'
}, {
  property: 'lte_rsrp',
  label: 'LTE_RSRP'
}, {
  property: 'lte_rsrq',
  label: 'LTE_RSRQ'
}, {
  property: 'lte_rssi',
  label: 'LTE_RSSI'
}, {
  property: 'lte_ci',
  label: 'LTE_CI'
}, {
  property: 'lte_pci',
  label: 'LTE_PCI'
}, {
  property: 'lte_tac',
  label: 'LTE_TAC'
}, {
  property: 'lte_snr',
  label: 'LTE_SNR'
}, {
  property: 'nr_strength',
  label: 'NR信号强度'
}, {
  property: 'nr_nci',
  label: 'NR_NCI'
}, {
  property: 'nr_pci',
  label: 'NR_PCI'
}, {
  property: 'nr_tac',
  label: 'NR_TAC'
}, {
  property: 'nr_csi_rsrp',
  label: 'NR_CSI_RSRP'
}, {
  property: 'nr_csi_rsrq',
  label: 'NR_CSI_RSRQ'
}, {
  property: 'nr_csi_sinr',
  label: 'NR_CSI_SINR'
}, {
  property: 'nr_ss_rsrp',
  label: 'NR_SS_RSRP'
}, {
  property: 'nr_ss_rsrq',
  label: 'NR_SS_RSRQ'
}]
