export const gpsEN = [{
  property: 'app_name',
  label: '软件名称'
}, {
  property: 'version',
  label: '版本号'
}, {
  property: 'tele_num',
  label: '手机号'
}, {
  property: 'unique_id',
  label: '设备ID'
}, {
  property: 'task_id',
  label: '业务ID'
}, {
  property: 'task_name',
  label: '业务名称'
}, {
  property: 'task',
  label: '业务类型'
}, {
  property: 'start_time',
  label: '开始时间'
}, {
  property: 'event_time',
  label: '测试时间'
}, {
  property: 'time',
  label: 'TIME'
}, {
  property: 'latitude',
  label: 'LATITUDE'
}, {
  property: 'longitude',
  label: 'LONGITUDE'
}, {
  property: 'altitude',
  label: 'ALTITUDE'
}, {
  property: 'speed',
  label: 'SPEED'
}, {
  property: 'network_type_id',
  label: 'NETWORK_TYPE_ID'
}, {
  property: 'network_name',
  label: 'NETWORK_NAME'
}, {
  property: 'network_info_id',
  label: 'NETWORK_INFO_ID'
}, {
  property: 'operator_id',
  label: 'OPERATOR_ID'
}, {
  property: 'operator',
  label: 'OPERATOR'
}, {
  property: 'internal_ip',
  label: 'INTERNAL_IP'
}, {
  property: 'external_ip',
  label: 'EXTERNAL_IP'
}, {
  property: 'wlan_ssid',
  label: 'WLAN_SSID'
}, {
  property: 'wlan_rssi',
  label: 'WLAN_RSSI'
}, {
  property: 'gsm_lac',
  label: 'GSM_LAC'
}, {
  property: 'gsm_cid',
  label: 'GSM_CID'
}, {
  property: 'gsm_rxqual',
  label: 'GSM_RXQUAL'
}, {
  property: 'cdma_strength',
  label: 'CDMA_STRENGTH'
}, {
  property: 'cdma_ecio',
  label: 'CDMA_Ec/Io'
}, {
  property: 'cdma_rssi',
  label: 'CDMA_RSSI'
}, {
  property: 'cdma_nid',
  label: 'CDMA_NID'
}, {
  property: 'cdma_bsid',
  label: 'CDMA_BSID'
}, {
  property: 'cdma_sid',
  label: 'CDMA_SID'
}, {
  property: 'evdo_snr',
  label: 'EVDO_SNR'
}, {
  property: 'evdo_ecio',
  label: 'EVDO_ECIO'
}, {
  property: 'evdo_rssi',
  label: 'EVDO_RSSI'
}, {
  property: 'wcdma_strength',
  label: 'WCDMA_STRENGTH'
}, {
  property: 'wcdma_rscp',
  label: 'WCDMA_RSCP'
}, {
  property: 'wcdma_rssi',
  label: 'WCDMA_RSSI'
}, {
  property: 'wcdma_ecno',
  label: 'WCDMA_Ec/No'
}, {
  property: 'wcdma_cid',
  label: 'WCDMA_CID'
}, {
  property: 'wcdma_lac',
  label: 'WCDMA_LAC'
}, {
  property: 'wcdma_psc',
  label: 'WCDMA_PSC'
}, {
  property: 'tdscdma_dbm',
  label: 'TDSCDMA_DBM'
}, {
  property: 'tdscdma_rssi',
  label: 'TDSCDMA_RSSI'
}, {
  property: 'tdscdma_cid',
  label: 'TDSCDMA_CID'
}, {
  property: 'tdscdma_cpid',
  label: 'TDSCDMA_CPID'
}, {
  property: 'tdscdma_lac',
  label: 'TDSCDMA_LAC'
}, {
  property: 'lte_rsrp',
  label: 'LTE_RSRP'
}, {
  property: 'lte_rsrq',
  label: 'LTE_RSRQ'
}, {
  property: 'lte_rssi',
  label: 'LTE_RSSI'
}, {
  property: 'lte_ci',
  label: 'LTE_CI'
}, {
  property: 'lte_pci',
  label: 'LTE_PCI'
}, {
  property: 'lte_tac',
  label: 'LTE_TAC'
}, {
  property: 'lte_snr',
  label: 'LTE_SNR'
}, {
  property: 'nr_strength',
  label: 'NR_STRENGTH'
}, {
  property: 'nr_nci',
  label: 'NR_NCI'
}, {
  property: 'nr_pci',
  label: 'NR_PCI'
}, {
  property: 'nr_tac',
  label: 'NR_TAC'
}, {
  property: 'nr_csi_rsrp',
  label: 'NR_CSI_RSRP'
}, {
  property: 'nr_csi_rsrq',
  label: 'NR_CSI_RSRQ'
}, {
  property: 'nr_csi_sinr',
  label: 'NR_CSI_SINR'
}, {
  property: 'nr_ss_rsrp',
  label: 'NR_SS_RSRP'
}, {
  property: 'nr_ss_rsrq',
  label: 'NR_SS_RSRQ'
}, {
  property: 'nr_ss_sinr',
  label: 'NR_SS_SINR'
}]
