export const ottBasic = [{
  property: 'app_name',
  label: '软件名称'
}, {
  property: 'version',
  label: '版本号'
}, {
  property: 'tele_num',
  label: '手机号'
}, {
  property: 'unique_id',
  label: '设备ID'
}, {
  property: 'task_id',
  label: '业务ID'
}, {
  property: 'task_name',
  label: '业务名称'
}, {
  property: 'task',
  label: '业务类型'
}, {
  property: 'start_time',
  label: '开始时间'
}, {
  property: 'event_time',
  label: '测试时间'
}, {
  property: 'app_version',
  label: '第三方app版本号'
}, {
  property: 'start_app_delay',
  label: '启动app时延ms'
}, {
  property: 'send_text_delay',
  label: '发送消息时延ms'
}, {
  property: 'send_text_result',
  label: '发送消息结果1表示成功'
}, {
  property: 'send_text_jitter_upload',
  label: '发送消息上行抖动值ms'
}, {
  property: 'send_text_jitter_download',
  label: '发送消息下行抖动值ms'
}, {
  property: 'send_text_pkg_count_upload',
  label: '发送消息上行包个数'
}, {
  property: 'send_text_pkg_count_download',
  label: '发送消息下行包个数'
}, {
  property: 'send_text_pkg_interval_upload',
  label: '发送消息上行包间隔ms'
}, {
  property: 'send_text_pkg_interval_download',
  label: '发送消息下行包间隔ms'
}, {
  property: 'send_text_byte_upload',
  label: '发送消息上行字节数byte'
}, {
  property: 'send_text_byte_download',
  label: '发送消息下行字节数byte'
}, {
  property: 'send_img_delay',
  label: '发送图片时延ms'
}, {
  property: 'send_img_result',
  label: '发送图片结果1表示成功'
}, {
  property: 'send_img_jitter_upload',
  label: '发送图片上行抖动值ms'
}, {
  property: 'send_img_jitter_download',
  label: '发送图片下行抖动值ms'
}, {
  property: 'send_img_pkg_count_upload',
  label: '发送图片上行包个数'
}, {
  property: 'send_img_pkg_count_download',
  label: '发送图片下行包个数'
}, {
  property: 'send_img_pkg_interval_upload',
  label: '发送图片上行包间隔ms'
}, {
  property: 'send_img_pkg_interval_download',
  label: '发送图片下行包间隔ms'
}, {
  property: 'send_img_byte_upload',
  label: '发送图片上行字节数byte'
}, {
  property: 'send_img_byte_download',
  label: '发送图片下行字节数byte'
}, {
  property: 'send_voice_delay',
  label: '发送语音时延ms'
}, {
  property: 'send_voice_result',
  label: '发送语音结果1表示成功'
}, {
  property: 'send_voice_jitter_upload',
  label: '发送语音上行抖动值ms'
}, {
  property: 'send_voice_jitter_download',
  label: '发送语音下行抖动值ms'
}, {
  property: 'send_voice_pkg_count_upload',
  label: '发送语音上行包个数'
}, {
  property: 'send_voice_pkg_count_download',
  label: '发送语音下行包个数'
}, {
  property: 'send_voice_pkg_interval_upload',
  label: '发送语音上行包间隔ms'
}, {
  property: 'send_voice_pkg_interval_download',
  label: '发送语音下行包间隔ms'
}, {
  property: 'send_voice_byte_upload',
  label: '发送语音上行字节数byte'
}, {
  property: 'send_voice_byte_download',
  label: '发送语音下行字节数byte'
}, {
  property: 'send_video_delay',
  label: '发送视频时延ms'
}, {
  property: 'send_video_result',
  label: '发送视频结果1表示成功'
}, {
  property: 'send_video_jitter_upload',
  label: '发送视频上行抖动值ms'
}, {
  property: 'send_video_jitter_download',
  label: '发送视频下行抖动值ms'
}, {
  property: 'send_video_pkg_count_upload',
  label: '发送视频上行包个数'
}, {
  property: 'send_video_pkg_count_download',
  label: '发送视频下行包个数'
}, {
  property: 'send_video_pkg_interval_upload',
  label: '发送视频上行包间隔ms'
}, {
  property: 'send_video_pkg_interval_download',
  label: '发送视频下行包间隔ms'
}, {
  property: 'send_video_byte_upload',
  label: '发送视频上行字节数byte'
}, {
  property: 'send_video_byte_download',
  label: '发送视频下行字节数byte'
}, {
  property: 'send_file_delay',
  label: '发送文件时延ms'
}, {
  property: 'send_file_result',
  label: '发送文件结果1表示成功'
}, {
  property: 'send_file_jitter_upload',
  label: '发送文件上行抖动值ms'
}, {
  property: 'send_file_jitter_download',
  label: '发送文件下行抖动值ms'
}, {
  property: 'send_file_pkg_count_upload',
  label: '发送文件上行包个数'
}, {
  property: 'send_file_pkg_count_download',
  label: '发送文件下行包个数'
}, {
  property: 'send_file_pkg_interval_upload',
  label: '发送文件上行包间隔ms'
}, {
  property: 'send_file_pkg_interval_download',
  label: '发送文件下行包间隔ms'
}, {
  property: 'send_file_byte_upload',
  label: '发送文件上行字节数byte'
}, {
  property: 'send_file_byte_download',
  label: '发送文件下行字节数byte'
}, {
  property: 'browse_friends_circle_img_delay',
  label: '浏览朋友圈图片时延ms'
}, {
  property: 'browse_friends_circle_img_result',
  label: '浏览朋友圈图片结果1表示成功'
}, {
  property: 'browse_friends_circle_img_jitter_upload',
  label: '浏览朋友圈图片上行抖动值ms'
}, {
  property: 'browse_friends_circle_img_jitter_download',
  label: '浏览朋友圈图片下行抖动值ms'
}, {
  property: 'browse_friends_circle_img_pkg_count_upload',
  label: '浏览朋友圈图片上行包个数'
}, {
  property: 'browse_friends_circle_img_pkg_count_download',
  label: '浏览朋友圈图片下行包个数'
}, {
  property: 'browse_friends_circle_img_pkg_interval_upload',
  label: '浏览朋友圈图片上行包间隔ms'
}, {
  property: 'browse_friends_circle_img_pkg_interval_download',
  label: '浏览朋友圈图片下行包间隔ms'
}, {
  property: 'browse_friends_circle_img_byte_upload',
  label: '浏览朋友圈图片上行字节数byte'
}, {
  property: 'browse_friends_circle_img_byte_download',
  label: '浏览朋友圈图片下行字节数byte'
}, {
  property: 'failed_reason_code',
  label: '失败原因码'
}, {
  property: 'failed_reason',
  label: '失败原因'
}, {
  property: 'sign_id',
  label: 'signId'
}, {
  property: 'select_action',
  label: '选择动作(发消息-发图片-发语音-发视频-发文件-浏览朋友圈)1表示执行'
}, {
  property: 'province',
  label: '省份'
}, {
  property: 'city',
  label: '城市'
}, {
  property: 'address',
  label: '详细地址'
}, {
  property: 'latitude',
  label: '纬度'
}, {
  property: 'longitude',
  label: '经度'
}, {
  property: 'source',
  label: '定位来源'
}, {
  property: 'network_type_id',
  label: '网络类型id'
}, {
  property: 'network_name',
  label: '网络类型名'
}, {
  property: 'network_info_id',
  label: '网络信息类型ID'
}, {
  property: 'operator_id',
  label: '运营商id'
}, {
  property: 'operator',
  label: '运营商标识'
}, {
  property: 'internal_ip',
  label: '内网ip'
}, {
  property: 'external_ip',
  label: '外网ip'
}, {
  property: 'wlan_ssid',
  label: 'WLAN_SSID'
}, {
  property: 'wlan_rssi',
  label: 'WLAN_RSSI'
}, {
  property: 'gsm_lac',
  label: 'GSM_LAC'
}, {
  property: 'gsm_cid',
  label: 'GSM_CID'
}, {
  property: 'gsm_rxqual',
  label: 'GSM_RXQUAL'
}, {
  property: 'cdma_strength',
  label: 'CDMA场强'
}, {
  property: 'cdma_ecio',
  label: 'CDMA_Ec/Io'
}, {
  property: 'cdma_rssi',
  label: 'CDMA_RSSI'
}, {
  property: 'cdma_nid',
  label: 'CDMA_NID'
}, {
  property: 'cdma_bsid',
  label: 'CDMA_BSID'
}, {
  property: 'cdma_sid',
  label: 'CDMA_SID'
}, {
  property: 'evdo_snr',
  label: 'EVDO_SNR'
}, {
  property: 'evdo_ecio',
  label: 'EVDO_ECIO'
}, {
  property: 'evdo_rssi',
  label: 'EVDO_RSSI'
}, {
  property: 'wcdma_strength',
  label: 'WCDMA信号强度'
}, {
  property: 'wcdma_rscp',
  label: 'WCDMA_RSCP'
}, {
  property: 'wcdma_rssi',
  label: 'WCDMA_RSSI'
}, {
  property: 'wcdma_ecno',
  label: 'WCDMA_Ec/No'
}, {
  property: 'wcdma_cid',
  label: 'WCDMA_CID'
}, {
  property: 'wcdma_lac',
  label: 'WCDMA_LAC'
}, {
  property: 'wcdma_psc',
  label: 'WCDMA_PSC'
}, {
  property: 'tdscdma_dbm',
  label: 'TDSCDMA_DBM'
}, {
  property: 'tdscdma_rssi',
  label: 'TDSCDMA_RSSI'
}, {
  property: 'tdscdma_cid',
  label: 'TDSCDMA_CID'
}, {
  property: 'tdscdma_cpid',
  label: 'TDSCDMA_CPID'
}, {
  property: 'tdscdma_lac',
  label: 'TDSCDMA_LAC'
}, {
  property: 'lte_rsrp',
  label: 'LTE_RSRP'
}, {
  property: 'lte_rsrq',
  label: 'LTE_RSRQ'
}, {
  property: 'lte_rssi',
  label: 'LTE_RSSI'
}, {
  property: 'lte_ci',
  label: 'LTE_CI'
}, {
  property: 'lte_pci',
  label: 'LTE_PCI'
}, {
  property: 'lte_tac',
  label: 'LTE_TAC'
}, {
  property: 'lte_snr',
  label: 'LTE_SNR'
}, {
  property: 'nr_strength',
  label: 'NR信号强度'
}, {
  property: 'nr_nci',
  label: 'NR_NCI'
}, {
  property: 'nr_pci',
  label: 'NR_PCI'
}, {
  property: 'nr_tac',
  label: 'NR_TAC'
}, {
  property: 'nr_csi_rsrp',
  label: 'NR_CSI_RSRP'
}, {
  property: 'nr_csi_rsrq',
  label: 'NR_CSI_RSRQ'
}, {
  property: 'nr_csi_sinr',
  label: 'NR_CSI_SINR'
}, {
  property: 'nr_ss_rsrp',
  label: 'NR_SS_RSRP'
}, {
  property: 'nr_ss_rsrq',
  label: 'NR_SS_RSRQ'
}]
